codecov:
  notify:
    require_ci_to_pass: yes
  token: b4c3edc4-41bb-4b20-bb6c-43380545aebb
coverage:
  precision: 5
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
