---
geometry: top=0.85in, left=1in, footskip=0.85in
indent: true
eqnos-capitalise: true
header-includes:
  \usepackage{microtype}
  \usepackage{mathpazo}
  \usepackage{palatino}
  \usepackage{sectsty}
  \usepackage{tikz}
  \usetikzlibrary{shapes.geometric, arrows}
  \sectionfont{\normalfont\sffamily}
  \subsectionfont{\normalfont\sffamily}
  \subsubsectionfont{\normalfont\sffamily\itshape}

---
