# pdflatex growth.tex && bibtex growth && pdflatex growth.tex
pandoc default.yaml -i dilution_derivation.md -F pandoc-mermaid --filter=pandoc-eqnos --filter=pandoc-crossref -o dilution_derivation.pdf
